### ISSUE TITLE
Binding value in code behind

### ISSUE THREAD

**Issue by MattePozzy** [ice-j/DateTimePicker#2]
Hi, I need to set a default value to the control using the BindingContext.

I've tried to make public static the BindableProperty DateTimeProperty and, in my page run this code:

    DateTimePicker DTpicker = new DateTimePicker() {
                VerticalOptions = LayoutOptions.CenterAndExpand,
                HorizontalOptions = LayoutOptions.FillAndExpand
            };
    DTpicker.SetBinding(DateTimePicker.DateTimeProperty, new Binding("BindingContext.dt_inizioIntervento", source: this));
Where `dt_inizioIntervento` is a DateTime value.

But nothing happens.

How can I do this?

**Comment by ice-j** [comment]
Can you provide a simple example project where I can reproduce this so I can take a look and debug it, please?

**Comment by MattePozzy** [comment]
Hi,
[here ](https://ufile.io/utans)a zip with full solution.
The page is in PCL -> Pages -> WorkOrder -> AggiungiRigaWO -> 1_Riga_Data.

When you start the application do the login with volos/volos, then select one of the list record and the page will open.

**Comment by ice-j** [comment]
Thanks, I will look into this later today and get back to you. Hopefully with a solution 😄

**Comment by ice-j** [comment]
Hi again,
Sorry for late response. 
I've seen your solution and the problem is that you don't have an assigned a binding context to the `AggiungiRigaWOData` content view.

So changing the lines 
> CarouselView.ItemsSource = new ObservableCollection<DataTemplate>() { // Popolo la lista delle slide da utlizzare nel "Wizard"
>                new DataTemplate(() => { return new AggiungiRigaWOData(); }),
>                new DataTemplate(() => { return new AggiungiRigaWOViaggioAndata(); })
>            };

with

>CarouselView.ItemsSource = new ObservableCollection<DataTemplate>() { // Popolo la lista delle slide da utlizzare nel "Wizard"
>                new DataTemplate(() => { return new AggiungiRigaWOData() { BindingContext = >_AggiungiRigaWOViewModel.WoSel }; }),
>                new DataTemplate(() => { return new AggiungiRigaWOViaggioAndata(); })
> };

 
in the `AggiungiRigaWO` page fixes your problem.
